### ISSUE TITLE
Selector does not synchronise to external state

### ISSUE THREAD

**Issue by timovandeput** [guidotheelen/number_selector#1]
This component is maintaining its internal state, instead of allowing it to be updated externally: When I change the `current` parameter in the widget constructor, the field does not follow this change.

This renders this widget quite useless for contexts where the current value is also changed by external factors.

Suggestion: Implement `didUpdateWidget()`, and respond to updated widget parameters.

**Comment by guidotheelen** [comment]
Thanks for addressing this issue kind sir! 😉 
Should be working correctly now ✨
